name: astro
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.5.1
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  envied: ^1.0.0
  equatable: ^2.0.5
  file_picker: 8.1.4
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  firebase_storage: ^12.3.0
  firebase_ui_auth: ^1.16.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  graphic: ^2.5.0
  http: ^1.2.2
  http_parser: ^4.0.2
  intl: ^0.19.0
  path_provider: ^2.1.4
  responsive_framework: ^1.5.1
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  syncfusion_flutter_charts: ^28.1.33

dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^1.0.0
  flutter_launcher_icons: ^0.14.1

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  logger: ^2.4.0

flutter:
  uses-material-design: true
