[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<=3.12"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "neuralprophet>=0.9.0",
    "python-multipart>=0.0.19",
]
